language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
install:
  - python setup.py install
script:
  - pwd
  - ls
  - echo ${TRAVIS_OS_NAME} ${TRAVIS_BUILD_DIR}
  - python -c "import tests; print(tests.__file__)" 
  - ls data
  - ls data/test_data
  - ls /home/travis/build/marshallmcdonnell/pystog/tests/../data
  - ls /home/travis/build/marshallmcdonnell/pystog/tests/../data/test_data/
  - python tests/runner.py
