language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install codecov
  - pip install flake8
script:
  - flake8 .
  - python tests/runner.py
  - coverage run tests/runner.py
after_success:
  - codecov
